#!/usr/bin/env bash
#
#
VERSION="1.0.1"
#sudo chown $USER:$USER fe-pi/*
[[ -s /etc/asound.conf ]] && sudo mv /etc/asound.conf /etc/asound.conf.previous
sudo cp -f fe-pi/etc/asound.conf /etc/
[[ -s /etc/pulse/default.pa ]] && sudo mv /etc/pulse/default.pa /etc/pulse/default.pa.previous
sudo cp -f fe-pi/etc/pulse/default.pa /etc/pulse/
# Append sound directives to the end of cmdline.txt to restore ALSA sound
# interface definitions using the old method (needed for compatibility with Fldigi
# alert sounds as well as to retain the ability to switch between HDMI and 
# Analog from the Desktop).
CMD_STRING="snd-bcm2835.enable_compat_alsa=1 snd-bcm2835.enable_hdmi=0 snd-bcm2835.enable_headphones=0"
if ! grep -q $CMD_STRING /boot/cmdline.txt 2>/dev/null
then
	sudo sed -i -e "s/$/ $CMD_STRING/" /boot/cmdline.txt
fi
